Taskk/Models/Entity/Personal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskk.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Phones = new HashSet<Phone>();
            Status = true;
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string BirthDay { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phone> Phones { get; set; }
    }
}

Taskk/Controllers/PersonalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Taskk.Models.Entity;
namespace Taskk.Controllers
{
    public class PersonalController : Controller
    {
        TaskDatabaseEntities1 db = new TaskDatabaseEntities1();
        // GET: Personal
        public ActionResult PersonalList()
        {
            var degerler = db.Personals.Where(m=>m.Status ==true).ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult AddPersonal()
        {
        
            return View();
        }
        [HttpPost]
        public ActionResult AddPersonal(Personal p1)
        {
            if (!ModelState.IsValid)
            {
                return View("AddPersonal");
            }
            db.Personals.Add(p1);
            db.SaveChanges();
            return RedirectToAction("PersonalList");
        }
        public ActionResult DeletePersonal(int id)
        {
            var personal = db.Personals.Find(id);
            //db.Personals.Remove(personal);
            personal.Status = false;
            db.SaveChanges();
            return RedirectToAction("PersonalList");
        }
        [HttpGet]
        public ActionResult GetPersonal(int id)
        {
            var prsnl = db.Personals.Find(id);
            return View(prsnl);
        }
        [HttpPost]
        public ActionResult UpdatePersonal(Personal p1)
        {
            var personel = db.Personals.Find(p1.ID);
            personel.Name = p1.Name;
            personel.Surname = p1.Surname;
            personel.Email = p1.Email;
            personel.BirthDay = p1.BirthDay;
            db.SaveChanges();
            return RedirectToAction("PersonalList");

        }
    }
}

Taskk/Views/Personal/AddPersonal.cshtml
@model Taskk.Models.Entity.Personal
@{
    ViewBag.Title = "AddPersonal";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    @*<div>
        <label>Personel Adı</label>
        <input type="text" class="form-control" name="Name" />
        <label>Personel Soyadı</label>
        <input type="text" class="form-control" name="Surname" />
        <label>Personel Email</label>
        <input type="text" class="form-control" name="Email" />
        <label>Personel Doğum Tarihi</label>
        <input type="text" class="form-control" name="Birthday" />
    </div>*@
    <div>
        <label>Personel Adı</label>
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name, "", new { @style = "color:red" })
        <br />
        <label>Personel Soyadı</label>
        @Html.TextBoxFor(m => m.Surname, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Surname, "", new { @style = "color:red" })
        <br />
        <label>Personel Emaili</label>
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Email, "", new { @style = "color:red" })
        <br />
        <label>Personel Doğum Tarihi</label>
        @Html.TextBoxFor(m => m.BirthDay, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.BirthDay, "", new { @style = "color:red" })
        <br />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Personel Ekle</button>
    </div>


</form>

Taskk/Views/Personal/GetPersonal.cshtml
@model Taskk.Models.Entity.Personal
@{
    ViewBag.Title = "GetPersonal";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("UpdatePersonal", "Personal", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.ID)
        @Html.TextBoxFor(m => m.ID, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Surname)
        @Html.TextBoxFor(m => m.Surname, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email)
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.BirthDay)
        @Html.TextBoxFor(m => m.BirthDay, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

Taskk/Views/Personal/PersonalList.cshtml
@using Taskk.Models.Entity
@model List<Personal>
@{
    ViewBag.Title = "PersonalList";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Personal Id</th>
        <th>Personal Name</th>
        <th>Personal Surname</th>
        <th>Personal Email</th>
        <th>Personal BirhDay</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    <tbody>
        @foreach (var prs in Model)
        {
        <tr>
            <th>@prs.ID</th>
            <td>@prs.Name</td>
            <td>@prs.Surname</td>
            <td>@prs.Email</td>
            <td>@prs.BirthDay</td>
            <td><a href="/Personal/DeletePersonal/@prs.ID" class="btn btn-danger">SİL</a></td>
            <td><a href="/Personal/GetPersonal/@prs.ID" class="btn btn-success">GÜNCELLE</a></td>

        </tr>
        }
    </tbody>

</table>
<a href="/Personal/AddPersonal/" class="btn btn-primary">Yeni Personel Ekle</a>